// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/role/role.proto

package go_micro_srv_basic_role

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_26e011caf756e89c, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type GetRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_26e011caf756e89c, []int{1}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Access               []string `protobuf:"bytes,2,rep,name=access,proto3" json:"access,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_26e011caf756e89c, []int{2}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetResponse) GetAccess() []string {
	if m != nil {
		return m.Access
	}
	return nil
}

func (m *GetResponse) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type RoleAddOrUpdateRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleAddOrUpdateRequest) Reset()         { *m = RoleAddOrUpdateRequest{} }
func (m *RoleAddOrUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*RoleAddOrUpdateRequest) ProtoMessage()    {}
func (*RoleAddOrUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_26e011caf756e89c, []int{3}
}

func (m *RoleAddOrUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleAddOrUpdateRequest.Unmarshal(m, b)
}
func (m *RoleAddOrUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleAddOrUpdateRequest.Marshal(b, m, deterministic)
}
func (m *RoleAddOrUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleAddOrUpdateRequest.Merge(m, src)
}
func (m *RoleAddOrUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_RoleAddOrUpdateRequest.Size(m)
}
func (m *RoleAddOrUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleAddOrUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoleAddOrUpdateRequest proto.InternalMessageInfo

func (m *RoleAddOrUpdateRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RoleAddOrUpdateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Response)(nil), "go.micro.srv.basic.role.Response")
	proto.RegisterType((*GetRequest)(nil), "go.micro.srv.basic.role.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "go.micro.srv.basic.role.GetResponse")
	proto.RegisterType((*RoleAddOrUpdateRequest)(nil), "go.micro.srv.basic.role.RoleAddOrUpdateRequest")
}

func init() { proto.RegisterFile("proto/role/role.proto", fileDescriptor_26e011caf756e89c) }

var fileDescriptor_26e011caf756e89c = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0xc1, 0x4e, 0x03, 0x21,
	0x14, 0x74, 0xa1, 0x69, 0xec, 0x6b, 0xe2, 0xe1, 0x25, 0xd6, 0x4d, 0x4f, 0x2b, 0x7a, 0xe8, 0x89,
	0x26, 0x7a, 0xf5, 0xe2, 0xa9, 0x47, 0x23, 0x89, 0x1f, 0x40, 0xe1, 0xc5, 0x90, 0xb4, 0x65, 0x05,
	0xec, 0xef, 0xf9, 0x6b, 0xa6, 0xcf, 0xb5, 0xeb, 0x61, 0xd7, 0x0b, 0x61, 0x60, 0x86, 0x99, 0xe1,
	0xc1, 0x75, 0x9b, 0x62, 0x89, 0xeb, 0x14, 0x77, 0xc4, 0x8b, 0x66, 0x8c, 0x37, 0xef, 0x51, 0xef,
	0x83, 0x4b, 0x51, 0xe7, 0x74, 0xd4, 0x5b, 0x9b, 0x83, 0xd3, 0xa7, 0x6b, 0x05, 0x70, 0x69, 0x28,
	0xb7, 0xf1, 0x90, 0x49, 0x35, 0x00, 0x1b, 0x2a, 0x86, 0x3e, 0x3e, 0x29, 0x17, 0x44, 0x98, 0x1c,
	0xec, 0x9e, 0xea, 0xaa, 0xa9, 0x56, 0x33, 0xc3, 0x7b, 0xf5, 0x0a, 0x73, 0x66, 0xfc, 0x08, 0x86,
	0x28, 0xb8, 0x80, 0xa9, 0x75, 0x8e, 0x72, 0xae, 0x45, 0x23, 0x57, 0x33, 0xd3, 0x21, 0x3e, 0x3f,
	0xda, 0x62, 0x53, 0x2d, 0x99, 0xdd, 0x21, 0xf5, 0x04, 0x0b, 0x13, 0x77, 0xf4, 0xec, 0xfd, 0x4b,
	0x7a, 0x6b, 0xbd, 0x2d, 0xf4, 0x1b, 0xe0, 0x0a, 0x44, 0xf0, 0xfc, 0xb6, 0x34, 0x22, 0xf8, 0xb3,
	0x9b, 0xe8, 0xdd, 0x1e, 0xbe, 0x2a, 0x98, 0x9c, 0xe4, 0x68, 0x40, 0x6e, 0xa8, 0xe0, 0x9d, 0x1e,
	0x29, 0xaa, 0xfb, 0x66, 0xcb, 0xfb, 0xff, 0x49, 0xdd, 0x6f, 0x5c, 0xa0, 0x83, 0xf9, 0x9f, 0x58,
	0xb8, 0x1e, 0x95, 0x0d, 0x17, 0x58, 0xde, 0x8e, 0x0b, 0xce, 0x26, 0xdb, 0x29, 0x0f, 0xe8, 0xf1,
	0x3b, 0x00, 0x00, 0xff, 0xff, 0x46, 0x96, 0x40, 0x61, 0xb9, 0x01, 0x00, 0x00,
}
