// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package go_micro_srv_basic_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthRequest struct {
	//id（账号）
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	//key (token)
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AuthRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type AuthResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ValidateRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateRequest) Reset()         { *m = ValidateRequest{} }
func (m *ValidateRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateRequest) ProtoMessage()    {}
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *ValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateRequest.Unmarshal(m, b)
}
func (m *ValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateRequest.Marshal(b, m, deterministic)
}
func (m *ValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateRequest.Merge(m, src)
}
func (m *ValidateRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateRequest.Size(m)
}
func (m *ValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateRequest proto.InternalMessageInfo

func (m *ValidateRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ValidateResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateResponse) Reset()         { *m = ValidateResponse{} }
func (m *ValidateResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateResponse) ProtoMessage()    {}
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *ValidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateResponse.Unmarshal(m, b)
}
func (m *ValidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateResponse.Marshal(b, m, deterministic)
}
func (m *ValidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateResponse.Merge(m, src)
}
func (m *ValidateResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateResponse.Size(m)
}
func (m *ValidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateResponse proto.InternalMessageInfo

func (m *ValidateResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{4}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Access               []string `protobuf:"bytes,2,rep,name=access,proto3" json:"access,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{5}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetResponse) GetAccess() []string {
	if m != nil {
		return m.Access
	}
	return nil
}

func (m *GetResponse) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "go.micro.srv.basic.user.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "go.micro.srv.basic.user.AuthResponse")
	proto.RegisterType((*ValidateRequest)(nil), "go.micro.srv.basic.user.ValidateRequest")
	proto.RegisterType((*ValidateResponse)(nil), "go.micro.srv.basic.user.ValidateResponse")
	proto.RegisterType((*GetRequest)(nil), "go.micro.srv.basic.user.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "go.micro.srv.basic.user.GetResponse")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x5f, 0x4f, 0x83, 0x30,
	0x14, 0xc5, 0x1d, 0xe0, 0xe2, 0xee, 0x8c, 0x2e, 0x37, 0xfe, 0x21, 0x3c, 0x11, 0x44, 0xc5, 0x97,
	0x2e, 0xd1, 0x4f, 0xe0, 0xd3, 0x9e, 0x25, 0x99, 0xef, 0x1d, 0xdc, 0x68, 0x33, 0x47, 0x67, 0x5b,
	0x96, 0xf8, 0x3d, 0xfc, 0xc0, 0x86, 0x52, 0x9c, 0x31, 0x43, 0xf7, 0x42, 0x7a, 0x2e, 0xbf, 0x73,
	0xe0, 0x9e, 0x14, 0xce, 0xd7, 0x4a, 0x1a, 0x39, 0xad, 0x35, 0x29, 0xfb, 0x60, 0x56, 0xe3, 0xe5,
	0x8b, 0x64, 0x2b, 0x51, 0x28, 0xc9, 0xb4, 0xda, 0xb0, 0x05, 0xd7, 0xa2, 0x60, 0xcd, 0xeb, 0x64,
	0x0a, 0xe3, 0xc7, 0xda, 0xbc, 0xe6, 0xf4, 0x5e, 0x93, 0x36, 0x78, 0x02, 0x9e, 0x28, 0xc3, 0x41,
	0x3c, 0xc8, 0x46, 0xb9, 0x27, 0x4a, 0x9c, 0x80, 0xbf, 0xa4, 0x8f, 0xd0, 0xb3, 0x83, 0xe6, 0x98,
	0xa4, 0x70, 0xdc, 0x1a, 0xf4, 0x5a, 0x56, 0x9a, 0xf0, 0x0c, 0x0e, 0x8d, 0x5c, 0x52, 0xe5, 0x4c,
	0xad, 0x48, 0x6e, 0xe1, 0xf4, 0x99, 0xbf, 0x89, 0x92, 0x1b, 0xea, 0xa2, 0x77, 0x83, 0x37, 0x30,
	0xd9, 0x82, 0x2e, 0x12, 0x21, 0xa8, 0xf8, 0x8a, 0x1c, 0x68, 0xcf, 0x49, 0x0c, 0x30, 0x23, 0xd3,
	0x65, 0xed, 0x22, 0x9e, 0x60, 0x6c, 0x89, 0xfe, 0x10, 0xbc, 0x80, 0x21, 0x2f, 0x0a, 0xd2, 0x3a,
	0xf4, 0x62, 0x3f, 0x1b, 0xe5, 0x4e, 0xd9, 0xf9, 0x86, 0x1b, 0xae, 0x42, 0xdf, 0xd2, 0x4e, 0xdd,
	0x7f, 0x7a, 0x10, 0xcc, 0x35, 0x29, 0x9c, 0x43, 0xd0, 0x2c, 0x8d, 0x29, 0xeb, 0xe9, 0x91, 0xfd,
	0x28, 0x31, 0xba, 0xfe, 0x87, 0x6a, 0xff, 0x30, 0x39, 0x40, 0x0e, 0x47, 0xdd, 0xf2, 0x98, 0xf5,
	0x9a, 0x7e, 0x15, 0x19, 0xdd, 0xed, 0x41, 0x7e, 0x7f, 0x22, 0x07, 0x7f, 0x46, 0x06, 0xaf, 0x7a,
	0x3d, 0xdb, 0x56, 0xa3, 0xf4, 0x6f, 0xa8, 0xcb, 0x5c, 0x0c, 0xed, 0x9d, 0x7a, 0xf8, 0x0a, 0x00,
	0x00, 0xff, 0xff, 0x0b, 0xa0, 0xff, 0xdf, 0x6c, 0x02, 0x00, 0x00,
}
